version: '3'

services: 
  
  publisher:
    build: 
      context: .
      dockerfile: ./publisher.dockerfile
    container_name: publisher
    ports: 
      - 8000:8000
    volumes: 
      - ./:/app
    depends_on:
      - redis-server
    networks: 
      - publisher-network

  redis-server:
    image: redis:6.0.12-alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redisdata:/usr/local/etc/redis
    networks: 
      - publisher-network

networks: 
  publisher-network:
    driver: bridge